// frontend/src/components/ptable/PrescriptionTable.tsx
/// <reference types="vite-plugin-svgr/client" />
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import AscSort from "@/assets/ascSortArrow.svg?react";
import DscSort from "@/assets/dscSortArrow.svg?react";
import DefaultSort from "@/assets/defaultSort.svg?react";
import {
  generatePrescriptionTemplate,
  Prescription,
} from "@/shared/types/Prescription";
import { stringToUSDate } from "@/shared/util/Date";

import {
  createColumnHelper,
  flexRender,
  getCoreRowModel,
  getSortedRowModel,
  SortingState,
  useReactTable,
} from "@tanstack/react-table";
import { useState } from "react";

interface PrescriptionTableProps {
  data: Prescription[] | undefined;
}

const tableHeaders = Object.keys(generatePrescriptionTemplate());

const PrescriptionTable: React.FC<PrescriptionTableProps> = ({ data }) => {
  const [hover, setHover] = useState("");
  //   const [sortState, setSortState] = useState("default");
  const [sorting, setSorting] = useState<SortingState>([]);
  const columnHelper = createColumnHelper<Prescription>();

  const columns = tableHeaders.map((h) => {
    if (h === "ended" || h === "started") {
      return columnHelper.accessor(h, {
        cell: (info) => stringToUSDate(info.getValue()),
        header: () => {
          // sorting[0].id == h && s
          if (sorting.length === 0 || sorting[0].id !== h) {
            return (
              <span>
                <DefaultSort className={"inline-block"} /> {h.toUpperCase()}
              </span>
            );
          }
          return sorting[0].desc ? (
            <span>
              <DscSort className={"inline-block"} />
              {h.toUpperCase()}
            </span>
          ) : (
            <span>
              <AscSort className={"inline-block"} />
              {h.toUpperCase()}
            </span>
          );
        },
      });
    }
    return columnHelper.accessor(h, {
      cell: (info) => info.getValue(),
      header: () => {
        // sorting[0].id == h && s
        if (sorting.length === 0 || sorting[0].id !== h) {
          return (
            <span>
              <DefaultSort className={"inline-block"} /> {h.toUpperCase()}
            </span>
          );
        }
        return sorting[0].desc ? (
          <span>
            <DscSort className={"inline-block"} />
            {h.toUpperCase()}
          </span>
        ) : (
          <span>
            <AscSort className={"inline-block"} />
            {h.toUpperCase()}
          </span>
        );
      },
    });
  });

  const table = useReactTable({
    columns,
    data: data ?? [],
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    onSortingChange: (updater) => setSorting(updater),
    state: { sorting },
  });

  return (
    <Table>
      <TableHeader>
        {table.getHeaderGroups().map((headerGroup) => (
          <TableRow key={headerGroup.id}>
            {headerGroup.headers.map((header) => {
              if (header.isPlaceholder || header.id == "id") {
                return null;
              }

              return (
                <TableHead
                  key={header.id}
                  onClick={header.column.getToggleSortingHandler()}
                  onMouseEnter={() => setHover(header.id)}
                  onMouseLeave={() => setHover("")}
                  className={`
                    ${hover === header.id ? "text-black" : ""} 
                    ${
                      header.column.getCanSort()
                        ? "cursor-pointer select-none"
                        : ""
                    }`}
                >
                  <span>
                    {flexRender(
                      header.column.columnDef.header,
                      header.getContext()
                    )}
                  </span>
                </TableHead>
              );
            })}
          </TableRow>
        ))}
      </TableHeader>
      <TableBody>
        {table.getRowModel().rows.map((row) => (
          <TableRow key={row.id}>
            {row.getVisibleCells().map((cell) => {
              if (cell.column.id === "id") {
                return null;
              }
              if (cell.column.id === "ended") {
                return cell.getValue() == null ? (
                  <TableCell key={cell.id}>Current</TableCell>
                ) : (
                  <TableCell key={cell.id}>
                    {flexRender(cell.column.columnDef.cell, cell.getContext())}
                  </TableCell>
                );
              }

              return (
                <TableCell key={cell.id}>
                  {flexRender(cell.column.columnDef.cell, cell.getContext())}
                </TableCell>
              );
            })}
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
};

export default PrescriptionTable;

// frontend/src/lib/components/prescription/table/PrescriptionTable.svelte
<script lang="ts" generics="TData extends Prescription, TValue">
	import { createSvelteTable, FlexRender } from '$lib/components/ui/data-table/index.js';
	import * as Table from '$lib/components/ui/table/index.js';
	import {
		type RowSelectionState,
		type SortingState,
		getCoreRowModel,
		getSortedRowModel
	} from '@tanstack/table-core';
	import { columns } from './Columns.js';
	import { getPrescriptionContext } from '$lib/context/PrescriptionContext.js';
	import { type Prescription } from '$lib/types/Prescription.js';

	type DataTableProps<TData, TValue> = {
		rowSelection: RowSelectionState;
		// onRowSelectionChange?: (selection: RowSelectionState) => void;
	};

	let { rowSelection = $bindable() }: DataTableProps<TData, TValue> = $props();
	const prescriptions = getPrescriptionContext();
	let sorting = $state<SortingState>([]);

	const table = createSvelteTable({
		get data() {
			return prescriptions.current as TData[];
		},
		columns: columns<TData>(),
		getCoreRowModel: getCoreRowModel(),
		getSortedRowModel: getSortedRowModel(),
		onSortingChange: (updater) => {
			if (typeof updater === 'function') {
				sorting = updater(sorting);
			} else {
				sorting = updater;
			}
		},
		onRowSelectionChange: (updater) => {
			if (typeof updater === 'function') {
				rowSelection = updater(rowSelection);
			} else {
				rowSelection = updater;
			}
		},
		getRowId: (row: TData) => (row as Prescription).id,
		state: {
			get sorting() {
				return sorting;
			},
			get rowSelection() {
				return rowSelection;
			}
		}
	});
</script>

<div class="rounded-md border">
	<Table.Root>
		<Table.Header>
			{#each table.getHeaderGroups() as headerGroup (headerGroup.id)}
				<Table.Row>
					{#each headerGroup.headers as header (header.id)}
						<Table.Head>
							{#if !header.isPlaceholder}
								<FlexRender
									content={header.column.columnDef.header}
									context={header.getContext()}
								/>
							{/if}
						</Table.Head>
					{/each}
				</Table.Row>
			{/each}
		</Table.Header>
		<Table.Body>
			{#each table.getRowModel().rows as row (row.id)}
				<Table.Row data-state={row.getIsSelected() && 'selected'}>
					{#each row.getVisibleCells() as cell (cell.id)}
						<Table.Cell>
							<FlexRender content={cell.column.columnDef.cell} context={cell.getContext()} />
						</Table.Cell>
					{/each}
				</Table.Row>
			{:else}
				<Table.Row>
					<Table.Cell colspan={columns.length} class="h-24 text-center">No results.</Table.Cell>
				</Table.Row>
			{/each}
		</Table.Body>
	</Table.Root>
</div>
